### ISSUE TITLE
添加注意力后的yaml文件的修改疑问

### ISSUE THREAD

**Issue by WangRongsheng** [mohenghui/yolov5_attention#2]
在博文：[https://blog.csdn.net/weixin_43694096/article/details/124443059](https://blog.csdn.net/weixin_43694096/article/details/124443059) 1.1添加方式的第三步以后还修改了层数，您认为有必要没有？
![](https://img-blog.csdnimg.cn/60bca6e917c24490b503efad48c6c3cf.png#pic_center)

**Comment by mohenghui** [comment]
Yes, he is also right, but we can't say who is right and who is wrong, because where the attention mechanism can be added to improve is unknown
